// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ExecutorSchema struct {
	ExecutorType string
	WorkerID     string
	SchemaJson   json.RawMessage
}

type TaskRun struct {
	RunID         string
	WorkflowRunID string
	ParentRunID   string
	Depth         uint32
	Scope         string
	TaskName      string
	TemplateName  string
	TemplateType  string
	CreatedAt     time.Time
	Inputs        sql.NullString
	Status        sql.NullString
	Message       sql.NullString
	Outputs       sql.NullString
	Metrics       sql.NullString
	RetryCount    sql.NullInt32
	Deadline      sql.NullTime
	Token         uint64
	UpdatedAt     time.Time
}

type WorkflowRun struct {
	RunID          string
	Workflow       json.RawMessage
	CreatedAt      time.Time
	CronWorkflowID string
	Status         sql.NullString
	Message        sql.NullString
	Outputs        sql.NullString
	Metrics        sql.NullString
	Deadline       sql.NullTime
	Token          uint64
	UpdatedAt      time.Time
}
