// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO task_runs (run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, inputs, status, message, outputs, metrics, retry_count, deadline)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	RunID         string
	WorkflowRunID string
	ParentRunID   string
	Depth         uint32
	Scope         string
	TaskName      string
	TemplateName  string
	TemplateType  string
	Inputs        sql.NullString
	Status        sql.NullString
	Message       sql.NullString
	Outputs       sql.NullString
	Metrics       sql.NullString
	RetryCount    sql.NullInt32
	Deadline      sql.NullTime
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.RunID,
		arg.WorkflowRunID,
		arg.ParentRunID,
		arg.Depth,
		arg.Scope,
		arg.TaskName,
		arg.TemplateName,
		arg.TemplateType,
		arg.Inputs,
		arg.Status,
		arg.Message,
		arg.Outputs,
		arg.Metrics,
		arg.RetryCount,
		arg.Deadline,
	)
	return err
}

const createWorkflow = `-- name: CreateWorkflow :exec
INSERT INTO workflow_runs (run_id, workflow, cron_workflow_id, status, message, outputs, metrics, deadline)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkflowParams struct {
	RunID          string
	Workflow       json.RawMessage
	CronWorkflowID string
	Status         sql.NullString
	Message        sql.NullString
	Outputs        sql.NullString
	Metrics        sql.NullString
	Deadline       sql.NullTime
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflow,
		arg.RunID,
		arg.Workflow,
		arg.CronWorkflowID,
		arg.Status,
		arg.Message,
		arg.Outputs,
		arg.Metrics,
		arg.Deadline,
	)
	return err
}

const getTask = `-- name: GetTask :one
SELECT run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, created_at, inputs, status, message, outputs, metrics, retry_count, deadline, token, updated_at FROM task_runs WHERE run_id = ?
`

func (q *Queries) GetTask(ctx context.Context, runID string) (TaskRun, error) {
	row := q.db.QueryRowContext(ctx, getTask, runID)
	var i TaskRun
	err := row.Scan(
		&i.RunID,
		&i.WorkflowRunID,
		&i.ParentRunID,
		&i.Depth,
		&i.Scope,
		&i.TaskName,
		&i.TemplateName,
		&i.TemplateType,
		&i.CreatedAt,
		&i.Inputs,
		&i.Status,
		&i.Message,
		&i.Outputs,
		&i.Metrics,
		&i.RetryCount,
		&i.Deadline,
		&i.Token,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, created_at, inputs, status, message, outputs, metrics, retry_count, deadline, token, updated_at FROM task_runs WHERE run_id = ? FOR UPDATE
`

func (q *Queries) GetTaskForUpdate(ctx context.Context, runID string) (TaskRun, error) {
	row := q.db.QueryRowContext(ctx, getTaskForUpdate, runID)
	var i TaskRun
	err := row.Scan(
		&i.RunID,
		&i.WorkflowRunID,
		&i.ParentRunID,
		&i.Depth,
		&i.Scope,
		&i.TaskName,
		&i.TemplateName,
		&i.TemplateType,
		&i.CreatedAt,
		&i.Inputs,
		&i.Status,
		&i.Message,
		&i.Outputs,
		&i.Metrics,
		&i.RetryCount,
		&i.Deadline,
		&i.Token,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskIdentity = `-- name: GetTaskIdentity :one
SELECT run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, created_at, inputs, status, message, outputs, metrics, retry_count, deadline, token, updated_at FROM task_runs WHERE workflow_run_id = ? AND parent_run_id = ? AND scope = ? AND task_name = ?
`

type GetTaskIdentityParams struct {
	WorkflowRunID string
	ParentRunID   string
	Scope         string
	TaskName      string
}

func (q *Queries) GetTaskIdentity(ctx context.Context, arg GetTaskIdentityParams) (TaskRun, error) {
	row := q.db.QueryRowContext(ctx, getTaskIdentity,
		arg.WorkflowRunID,
		arg.ParentRunID,
		arg.Scope,
		arg.TaskName,
	)
	var i TaskRun
	err := row.Scan(
		&i.RunID,
		&i.WorkflowRunID,
		&i.ParentRunID,
		&i.Depth,
		&i.Scope,
		&i.TaskName,
		&i.TemplateName,
		&i.TemplateType,
		&i.CreatedAt,
		&i.Inputs,
		&i.Status,
		&i.Message,
		&i.Outputs,
		&i.Metrics,
		&i.RetryCount,
		&i.Deadline,
		&i.Token,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT run_id, workflow, created_at, cron_workflow_id, status, message, outputs, metrics, deadline, token, updated_at FROM workflow_runs WHERE run_id = ?
`

func (q *Queries) GetWorkflow(ctx context.Context, runID string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, runID)
	var i WorkflowRun
	err := row.Scan(
		&i.RunID,
		&i.Workflow,
		&i.CreatedAt,
		&i.CronWorkflowID,
		&i.Status,
		&i.Message,
		&i.Outputs,
		&i.Metrics,
		&i.Deadline,
		&i.Token,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowForUpdate = `-- name: GetWorkflowForUpdate :one
SELECT run_id, workflow, created_at, cron_workflow_id, status, message, outputs, metrics, deadline, token, updated_at FROM workflow_runs WHERE run_id = ? FOR UPDATE
`

func (q *Queries) GetWorkflowForUpdate(ctx context.Context, runID string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowForUpdate, runID)
	var i WorkflowRun
	err := row.Scan(
		&i.RunID,
		&i.Workflow,
		&i.CreatedAt,
		&i.CronWorkflowID,
		&i.Status,
		&i.Message,
		&i.Outputs,
		&i.Metrics,
		&i.Deadline,
		&i.Token,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, created_at, inputs, status, message, outputs, metrics, retry_count, deadline, token, updated_at FROM task_runs WHERE deadline IS NOT NULL AND (status IS NULL OR status NOT IN ('Succeeded','Failed','Error','Timeout','Skipped','Cancelled')) ORDER BY created_at, run_id
`

func (q *Queries) ListActiveTasks(ctx context.Context) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRun
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.RunID,
			&i.WorkflowRunID,
			&i.ParentRunID,
			&i.Depth,
			&i.Scope,
			&i.TaskName,
			&i.TemplateName,
			&i.TemplateType,
			&i.CreatedAt,
			&i.Inputs,
			&i.Status,
			&i.Message,
			&i.Outputs,
			&i.Metrics,
			&i.RetryCount,
			&i.Deadline,
			&i.Token,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorkflows = `-- name: ListActiveWorkflows :many
SELECT run_id, workflow, created_at, cron_workflow_id, status, message, outputs, metrics, deadline, token, updated_at FROM workflow_runs WHERE deadline IS NOT NULL AND (status IS NULL OR status NOT IN ('Succeeded','Failed','Error','Timeout','Skipped','Cancelled')) ORDER BY created_at, run_id
`

func (q *Queries) ListActiveWorkflows(ctx context.Context) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.RunID,
			&i.Workflow,
			&i.CreatedAt,
			&i.CronWorkflowID,
			&i.Status,
			&i.Message,
			&i.Outputs,
			&i.Metrics,
			&i.Deadline,
			&i.Token,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronWorkflowsRuns = `-- name: ListCronWorkflowsRuns :many
SELECT run_id, workflow, created_at, cron_workflow_id, status, message, outputs, metrics, deadline, token, updated_at FROM workflow_runs WHERE cron_workflow_id = ? ORDER BY created_at, run_id
`

func (q *Queries) ListCronWorkflowsRuns(ctx context.Context, cronWorkflowID string) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listCronWorkflowsRuns, cronWorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.RunID,
			&i.Workflow,
			&i.CreatedAt,
			&i.CronWorkflowID,
			&i.Status,
			&i.Message,
			&i.Outputs,
			&i.Metrics,
			&i.Deadline,
			&i.Token,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentTasks = `-- name: ListParentTasks :many
SELECT run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, created_at, inputs, status, message, outputs, metrics, retry_count, deadline, token, updated_at FROM task_runs WHERE workflow_run_id = ? AND parent_run_id = ? ORDER BY created_at, run_id
`

type ListParentTasksParams struct {
	WorkflowRunID string
	ParentRunID   string
}

func (q *Queries) ListParentTasks(ctx context.Context, arg ListParentTasksParams) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listParentTasks, arg.WorkflowRunID, arg.ParentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRun
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.RunID,
			&i.WorkflowRunID,
			&i.ParentRunID,
			&i.Depth,
			&i.Scope,
			&i.TaskName,
			&i.TemplateName,
			&i.TemplateType,
			&i.CreatedAt,
			&i.Inputs,
			&i.Status,
			&i.Message,
			&i.Outputs,
			&i.Metrics,
			&i.RetryCount,
			&i.Deadline,
			&i.Token,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemas = `-- name: ListSchemas :many
SELECT executor_type, worker_id, schema_json FROM executor_schemas ORDER BY executor_type, worker_id
`

func (q *Queries) ListSchemas(ctx context.Context) ([]ExecutorSchema, error) {
	rows, err := q.db.QueryContext(ctx, listSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutorSchema
	for rows.Next() {
		var i ExecutorSchema
		if err := rows.Scan(&i.ExecutorType, &i.WorkerID, &i.SchemaJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT run_id, workflow_run_id, parent_run_id, depth, scope, task_name, template_name, template_type, created_at, inputs, status, message, outputs, metrics, retry_count, deadline, token, updated_at FROM task_runs WHERE workflow_run_id = ? ORDER BY created_at, run_id
`

func (q *Queries) ListTasks(ctx context.Context, workflowRunID string) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRun
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.RunID,
			&i.WorkflowRunID,
			&i.ParentRunID,
			&i.Depth,
			&i.Scope,
			&i.TaskName,
			&i.TemplateName,
			&i.TemplateType,
			&i.CreatedAt,
			&i.Inputs,
			&i.Status,
			&i.Message,
			&i.Outputs,
			&i.Metrics,
			&i.RetryCount,
			&i.Deadline,
			&i.Token,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE task_runs SET inputs = COALESCE(?, inputs), status = COALESCE(?, status), message = COALESCE(?, message), outputs = COALESCE(?, outputs), metrics = COALESCE(?, metrics), retry_count = COALESCE(?, retry_count), deadline = COALESCE(?, deadline), token = token + 1, updated_at = CURRENT_TIMESTAMP(6)
WHERE run_id = ? AND token = CAST(? AS CHAR) AND token < 18446744073709551615
`

type UpdateTaskParams struct {
	Inputs     sql.NullString
	Status     sql.NullString
	Message    sql.NullString
	Outputs    sql.NullString
	Metrics    sql.NullString
	RetryCount sql.NullInt32
	Deadline   sql.NullTime
	RunID      string
	Column9    interface{}
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Inputs,
		arg.Status,
		arg.Message,
		arg.Outputs,
		arg.Metrics,
		arg.RetryCount,
		arg.Deadline,
		arg.RunID,
		arg.Column9,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkflow = `-- name: UpdateWorkflow :execrows
UPDATE workflow_runs SET status = COALESCE(?, status), message = COALESCE(?, message),
 outputs = COALESCE(?, outputs), metrics = COALESCE(?, metrics), deadline = COALESCE(?, deadline),
 token = token + 1, updated_at = CURRENT_TIMESTAMP(6)
WHERE run_id = ? AND token = CAST(? AS CHAR) AND token < 18446744073709551615
`

type UpdateWorkflowParams struct {
	Status   sql.NullString
	Message  sql.NullString
	Outputs  sql.NullString
	Metrics  sql.NullString
	Deadline sql.NullTime
	RunID    string
	Column7  interface{}
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkflow,
		arg.Status,
		arg.Message,
		arg.Outputs,
		arg.Metrics,
		arg.Deadline,
		arg.RunID,
		arg.Column7,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSchema = `-- name: UpsertSchema :exec
INSERT INTO executor_schemas (executor_type, worker_id, schema_json) VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE schema_json = VALUES(schema_json)
`

type UpsertSchemaParams struct {
	ExecutorType string
	WorkerID     string
	SchemaJson   json.RawMessage
}

func (q *Queries) UpsertSchema(ctx context.Context, arg UpsertSchemaParams) error {
	_, err := q.db.ExecContext(ctx, upsertSchema, arg.ExecutorType, arg.WorkerID, arg.SchemaJson)
	return err
}
